name: Codeception Tests

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Pass1234@
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: 
          MYSQL_PASSWORD: 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: $
          extensions: pdo, pdo_mysql
          tools: composer:v2

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h mysql --silent; then
              break
            fi
            sleep 1
          done

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run Codeception tests
        env:
          DB_DSN: 'mysql:host=localhost;dbname=wordpress_test'
          DB_USER: 'root'
          DB_PASS: 'Pass1234@'
        run: php vendor/bin/codecept run
